spring.application.name=springbootwithjpql

spring.datasource.url = jdbc:mysql://localhost:3306/giftableddb
spring.datasource.username = root
spring.datasource.password = root

#hibernate config
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
